# Generated by Django 5.2.5 on 2025-11-20 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("roll_number", models.CharField(max_length=10, unique=True)),
                (
                    "course",
                    models.CharField(
                        choices=[
                            ("CS", "Computer Science"),
                            ("EE", "Electrical Engineering"),
                            ("ME", "Mechanical Engineering"),
                        ]
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ]
                    ),
                ),
                ("profile_url", models.URLField(blank=True)),
            ],
        ),
    ]
