# Generated by Django 5.2.5 on 2025-11-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="course",
            field=models.CharField(
                choices=[
                    ("CS", "Computer Science"),
                    ("EE", "Electrical Engineering"),
                    ("ME", "Mechanical Engineering"),
                    ("CE", "Civil Engineering"),
                ]
            ),
        ),
    ]
