# Generated by Django 5.2.5 on 2025-11-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Blog",
            new_name="BlogPost",
        ),
    ]
