# Generated by Django 5.2.5 on 2025-11-18 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0002_rename_blog_blogpost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="expiry_date",
            new_name="expiration_date",
        ),
    ]
