# Generated by Django 5.2.5 on 2025-12-02 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Event name"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("fee", models.FloatField(default=0.0, null=True)),
                ("is_online", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "participant_name",
                    models.CharField(max_length=100, verbose_name="Participant Name"),
                ),
                ("participant_email", models.EmailField(max_length=254, null=True)),
                ("number_of_tickets", models.IntegerField(default=1)),
                (
                    "registered_at",
                    models.DateTimeField(null=True, verbose_name="Registered At"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.event",
                    ),
                ),
            ],
        ),
    ]
