# Generated by Django 5.2.5 on 2025-12-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Event Name"
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="participant_name",
            field=models.CharField(max_length=10, verbose_name="Participant Name"),
        ),
        migrations.AlterField(
            model_name="registration",
            name="registered_at",
            field=models.DateTimeField(null=True, verbose_name="Registered at"),
        ),
    ]
