# Generated by Django 5.2.5 on 2025-12-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                (
                    "class_level",
                    models.CharField(
                        choices=[
                            ("1", "Class 1"),
                            ("2", "Class 2"),
                            ("3", "Class 3"),
                            ("4", "Class 4"),
                            ("5", "Class 5"),
                        ]
                    ),
                ),
                (
                    "favourite_subject",
                    models.CharField(
                        choices=[
                            ("maths", "Mathematics"),
                            ("science", "Science"),
                            ("eng", "English"),
                            ("history", "History"),
                            ("art", "Arts"),
                        ]
                    ),
                ),
            ],
        ),
    ]
