# Generated by Django 5.2.5 on 2025-11-18 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("toDo_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ToDo",
            new_name="Tasks",
        ),
    ]
