# Generated by Django 5.2.5 on 2025-11-20 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=100)),
                (
                    "publication_year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1800),
                            django.core.validators.MaxValueValidator(2023),
                        ]
                    ),
                ),
                ("isbn", models.CharField(max_length=13, unique=True)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("FIC", "Fiction"),
                            ("NON", "Non-Fiction"),
                            ("SCI", "Science"),
                            ("HIS", "History"),
                        ],
                        max_length=50,
                    ),
                ),
                ("website", models.URLField(blank=True)),
            ],
        ),
    ]
