# Generated by Django 5.2.5 on 2025-11-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campus", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="roll_number",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
