# Generated by Django 5.2.5 on 2025-11-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(default="Medium", max_length=50),
        ),
    ]
