# Generated by Django 5.2.5 on 2025-11-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe_app", "0002_recipe_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="state",
            field=models.CharField(default="Jharkhand", max_length=100),
        ),
    ]
