# Generated by Django 5.2.5 on 2025-11-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0002_product_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(),
        ),
    ]
